# syntax=docker/dockerfile:1
# hadolint ignore=DL3029
FROM --platform=$BUILDPLATFORM node:18-alpine AS builder

ARG TARGETPLATFORM
ARG BUILDPLATFORM

LABEL maintainer="Augen Dev team"

WORKDIR /app

COPY . /app

RUN npm install && npm run build

# Final image
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules/ ./node_modules/
COPY --from=builder /app/.next/ ./.next/
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/next-env.d.ts ./next-env.d.ts
COPY --from=builder /app/next.config.js ./next.config.js

CMD [ "npm", "run" , "start"]

EXPOSE 3000
